feat(user/route controller) add user endpoint and controller GET /user/allusers
miguelbel00/grupo-n-4 pull request #5
Opened 2022-11-03 00:10 UTC by miguelbel00

Post request and response at endpoint '/user/all'
![imagen](https://user-images.githubusercontent.com/55055505/199625103-051d39e2-9243-4db1-8751-210be40b5da8.png)

2022-11-03 12:47 UTC, miguelbel00 commented
Como Admin 
Quiero saber cuantos usuarios tengo
Para tener estadisticas

criterios de aceptacion 
GET /users - Deberia volver todos los usuarios, unicamente los campos de fisrtname, lastname,email y createdAt

![imagen](https://user-images.githubusercontent.com/55055505/199722894-4c7962dd-8871-4d50-8296-7bef5c4d14c1.png)

2022-11-03 13:14 UTC, IMatfres requested changes
change the name file controller, for userSearchController, to keep all the same context, and in the file index route, your route should be /users and you have /users/

2022-11-03 20:04 UTC, didierrevelo requested changes
delete example files models

2022-11-03 20:04 UTC, didierrevelo commented on routes/index.js
> -const categoryRoutes = require('./categoryRoutes')
is lacki the category`s import

2022-11-04 01:32 UTC, IMatfres approved these changes
All Ok

2022-11-04 20:37 UTC, didierrevelo requested changes
all ok

2022-11-04 20:37 UTC, didierrevelo approved these changes

2022-11-04 20:37 UTC, merged